---
slug: js2023
surveyId: js2023
id: js2023
context: state_of_js
topic: JavaScript
startedAt: November 1, 2023
endedAt: December 1, 2023
prettySlug: state-of-js
questionsUrl: https://survey.devographics.com/survey/state-of-js/2023
resultsUrl: https://2023.stateofjs.com/
year: 2023
status: 4 # preview/open/closed/hidden
imageUrl: https://devographics.github.io/surveys/state_of_js/js2023/images/js2023.png
faviconUrl: https://devographics.github.io/surveys/state_of_js/js2023/images/js2023-favicon.svg
socialImageUrl: https://devographics.github.io/surveys/state_of_js/js2023/images/js2023-og.png
domain: stateofjs.com
bgColor: rgb(34, 36, 41)
textColor: rgb(224, 228, 228)
linkColor: rgb(65, 199, 199)
hoverColor: rgb(254, 106, 106)
tags: [js]
credits:
  # - id: shawn_wang
  #   role: survey_design
  # - id: mark_erikson
  #   role: survey_design
faq:
  - data_used_js2023
  # - survey_design_js2023
  - results_released_js2023
  - team
  - questions_required
  - learn_more_js2023

colors:
  primary: rgb(71, 207, 237)
  secondary: "#8D4CA8"
  text: rgb(255, 246, 230)
  background: rgb(39, 35, 37)
  backgroundSecondary: rgb(48, 52, 53)

partners:
  - name: Nijibox
    id: nijibox
    url: https://www.nijibox.jp/
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2023/images/sponsors/nijibox.svg

sponsors:
  - name: Frontend Masters
    id: frontendmasters
    url: https://frontendmasters.com/?utm_source=stateofjs&utm_medium=website&utm_campaign=stateofjs2023
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2023/images/sponsors/frontend-masters-dark.png
  # - name: Polypane
  #   id: polypane
  #   url: https://polypane.app/
  #   imageUrl: https://devographics.github.io/surveys/state_of_css/css2023/images/sponsors/polypane.png
  - name: Google Chrome
    id: google_chrome
    url: https://www.google.com/chrome/?utm_source=stateofjs&utm_medium=website&utm_campaign=stateofjs2023
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2023/images/sponsors/google.png
  # - name: Nijibox
  #   id: nijibox
  #   url: https://www.nijibox.jp/?utm_source=stateofjs&utm_medium=website&utm_campaign=stateofjs2023
  #   imageUrl: https://devographics.github.io/surveys/state_of_css/css2023/images/sponsors/nijibox.svg
  - name: RenderATL
    id: renderatl
    url: https://www.renderatl.com/?utm_source=stateofjs&utm_medium=website&utm_campaign=stateofjs2023
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2023/images/sponsors/renderatl.png

tshirt:
  images: ["js2021-tshirt.jpg"]
  url: https://cottonbureau.com/products/javascript-retro-vhs
  price: 29
  designerUrl: https://chriskirknielsen.com/
