body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to propose a feature for the State of HTML 2023 survey! Please fill out the following information to help us understand the feature you're proposing.
        PLease make sure the feature is not already proposed by someone else, by browsing the [other proposed features](https://github.com/Devographics/surveys/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22State+of+HTML+2023%22).
  - type: textarea
    id: code
    attributes:
      label: Code sample
      description: Example HTML code (if you need to provide example JS or CSS, please do so in the "Details" section below, or within `<script>` or `<style>` in the code sample)
      render: html
  - type: input
    id: mdn_url
    attributes:
      label: "MDN URL:"
      description: URL to the MDN docs for this feature (if they exist)
      placeholder: ex. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/portal
  - type: input
    id: spec_url
    attributes:
      label: "Specification URL:"
      description: URL to the specification for this feature (if it exists and you have it). This could be a proposal, if no spec exists. Often listed in the MDN docs, right above the browser compatibility table.
      placeholder: ex. https://wicg.github.io/portals/#the-portal-element
  - type: textarea
    id: other_urls
    attributes:
      label: Any other links?
      description: These may be tutorials, blog posts, news coverage, tweets/toots/skeets, [caniuse](https://caniuse.com) links, or other resources that help explain the feature.
        One per line please.
  - type: dropdown
    id: stability
    attributes:
      label: How stable is this feature?
      description: While the survey skews towards more recent and cutting edge features,
        we do plan to ask about certain stable features as well,
        to see how widely they're used and some future ones to gauge interest.
        "Shipped" refers to features that are available in stable versions of browsers, without being behind a flag or origin trial.
      options:
        - Future (No implementations yet)
        - Near Future (No shipped implementations yet, but at least one behind a flag)
        - Cutting edge (Shipped, but not in all browsers)
        - Recent (Shipped in all major browsers)
        - Stable (Widely supported for several years)
        - Controversial (Some shipped implementations, but some browsers have declined to implement)
        - Deprecated (Still supported, but not recommended for use in new projects)
        - Removed (No longer supported in any major browsers)
  - type: dropdown
    id: type
    attributes:
      label: Type of feature
      description: |
        If not an HTML feature, please explain how it relates to the State of HTML survey in the "Details" section below.
        If it’s a combination, select all that apply.
        E.g. Canvas would fall under both "HTML element" and "JS API".
      multiple: true
      options:
        - HTML element
        - HTML attribute
        - HTML attribute value
        - JS API
        - CSS
        - HTTP
        - Separate file
        - Other
  - type: dropdown
    id: area
    attributes:
      label: What focus area does this feature fall into?
      description: Please select all that apply. If none apply, please select "Other" and explain in the "Details" section below.
      multiple: true
      options:
        - Forms
        - Consuming Web Components
        - Making Web Components
        - Accessibility
        - Security & Privacy
        - Performance
        - Embedding
        - Multimedia
        - Interactivity
        - Semantic HTML
        - Templating
        - Bridging the gap with native
        - Other
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Please provide more details, explain what asking about this feature teaches us about developers and the state of web development in 2023, how it relates to the State of HTML survey (if non-obvious), and any other information you think would be relevant.




