surveyId: graphql2022
startedAt: June 15, 2022
endedAt: July 15, 2022
shareUrl: https://stateofgraphql.com
questionsUrl: https://survey.devographics.com/survey/state-of-graphql/2022
# resultsUrl: https://2022.stateofgraphql.com/
year: 2022
status: 3 # preview/open/closed/hidden
imageUrl: https://devographics.github.io/surveys/state_of_graphql/2022/images/stateofgraphql2022-social.png
faviconUrl: https://devographics.github.io/surveys/state_of_graphql/2022/images/favicon.svg
socialImageUrl: https://devographics.github.io/surveys/state_of_graphql/2022/images/stateofgraphql2022-social.png

colors: 
  primary: "#F999D3"
  secondary: "#5C63E0"
  text: "#FFF6E6"
  background: "#263342"
  backgroundSecondary: "#2C4461"

credits:
  - id: eric_burel
    role: back_end_developement
  - id: christopher_kirk_nielsen
    role: logo_design
  - id: praveen_durairaju
    role: survey_design
  - id: benjie_gillam
    role: survey_design
  - id: uri_goldshtein
    role: survey_design
  - id: michael_hayes
    role: survey_design
  - id: charly_poly
    role: survey_design
  - id: phil_prasek
    role: survey_design
  - id: laurin_quast
    role: survey_design
  - id: john_p_vajda
    role: survey_design