query {
  surveys {
    state_of_devs {
      devs2026 {
        user_info {
          native_languages: native_languages {
            id
            comments {
              currentEdition {
                count
              }
            }
            _correlations {
              questionCorrelations {
                questionId1
                sectionId1
                optionId1
                questionId2
                sectionId2
                optionId2
                n
                correlation
                sameSection
                strength
                direction
              }
              optionCorrelations {
                id
                correlations {
                  questionId1
                  sectionId1
                  optionId1
                  questionId2
                  sectionId2
                  optionId2
                  n
                  correlation
                  sameSection
                  strength
                  direction
                }
              }
            }
            freeform(
              parameters: {
                showNoAnswer: true
                cutoff: 10
                limit: 40
                mergeOtherBuckets: true
              }
            ) {
              allEditions(editionCount: 2) {
                _metadata {
                  axis1Sort {
                    property
                    order
                  }
                  axis2Sort {
                    property
                    order
                  }
                  limit
                  cutoff
                }
                editionId
                year
                completion {
                  count
                  percentageSurvey
                  total
                }
                average
                percentiles {
                  p50
                }
                buckets {
                  count
                  id
                  value
                  index
                  percentageQuestion
                  percentageSurvey
                  isFreeformData
                  hasInsufficientData
                }
              }
            }
          }
        }
      }
    }
  }
}
