id: devs2026
feedbackAt: May 22, 2026
startedAt: June 22, 2026
endedAt: July 22, 2026
releasedAt: July 30, 2026
questionsUrl: https://survey.devographics.com/survey/state-of-devs/2026
feedbackUrl: https://github.com/Devographics/surveys/issues/288
resultsUrl: https://2026.state_of_devs.com/
year: 2026
status: 2 # preview/open/closed/hidden
resultsStatus: 1 # hidden/preview/published

enableReadingList: false
enableChartSponsorships: false
enableSkip: true

# credits:
# - id: sidney_brandhorst
#   role: survey_design
# - id: mark_erikson
#   role: survey_design
faq:
  - how_long_will_survey_take_devs2026
  - who_should_take_survey_devs
  - survey_goals_devs
  - data_used_devs
  - results_released_devs2026
  - team
  - survey_design_devs2026
  # - learn_more_js2024

colors:
  primary: rgb(71, 207, 237)
  secondary: "#8D4CA8"
  text: rgb(255, 246, 230)
  background: rgb(39, 35, 37)
  backgroundSecondary: rgb(48, 52, 53)

colorTheme:
  lightOnDark:
    primary:
      default: "#BDFDFF"
      darker: "#299295"
    background:
      default: "#2E3337"
      alt: "#29333a"
      alt2: "#2b343b"
    text:
      default: "#e2feff"
    experience:
      heard: "rgb(166, 223, 245)"
      used: "rgb(32, 146, 175)"
      never_heard: "rgb(128, 137, 139)"
    sentiment:
      positive: "rgb(92, 229, 186)"
      negative: "rgb(232, 64, 131)"
      neutral: "rgb(128, 137, 139)"
    velocity:
      - "hsl(182, 100%, 20%)"
      - "hsl(182, 100%, 25%)"
      - "hsl(182, 100%, 30%)"
      - "hsl(182, 100%, 35%)"
      - "hsl(182, 100%, 40%)"
      - "hsl(182, 100%, 45%)"
      - "hsl(182, 100%, 50%)"
      - "hsl(182, 100%, 55%)"
      - "hsl(182, 100%, 60%)"
      - "hsl(182, 100%, 65%)"
      - "hsl(182, 100%, 70%)"
      - "hsl(182, 100%, 75%)"
      - "hsl(182, 100%, 80%)"
      - "hsl(182, 100%, 85%)"

sponsors:
  - name: Polypane
    id: polypane
    url: https://polypane.app/
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2023/images/sponsors/polypane.png
  # - name: Google Chrome
  #   id: google_chrome
  #   url: https://www.google.com/chrome/?utm_source=state_of_devs&utm_medium=website&utm_campaign=devs2026
  #   imageUrl: https://assets.devographics.com/sponsors/google.png
  - name: TokyoDev
    id: tokyodev
    url: https://www.tokyodev.com/?utm_source=state_of_devs&utm_medium=website&utm_campaign=devs2026
    imageUrl: https://assets.devographics.com/sponsors/tokyodev.svg
  - name: Master.dev
    id: frontendmasters
    url: https://frontendmasters.com/?utm_source=state_of_devs&utm_medium=website&utm_campaign=devs2026
    imageUrl: https://assets.devographics.com/sponsors/masterdev.svg
  # - name: Algolia
  #   id: algolia
  #   url: https://www.algolia.com/?utm_source=state_of_devs&utm_medium=website&utm_campaign=devs2026
  #   imageUrl: https://assets.devographics.com/sponsors/algolia-logo-white.svg
  # - name: Storyblok
  #   id: storyblok
  #   url: https://www.storyblok.com/?utm_source=state_of_devs&utm_medium=website&utm_campaign=devs2026
  #   imageUrl: https://assets.devographics.com/sponsors/storyblok-light.svg
  - name: GitNation
    id: gitnation
    url: https://gitnation.com/?utm_source=state_of_devs&utm_medium=website&utm_campaign=devs2026
    imageUrl: https://assets.devographics.com/sponsors/GitNation-orange.svg
  - name: Certificates.dev
    id: certificates_dev
    url: https://certificates.dev?friend=Devographics&utm_source=state_of_devs&utm_medium=website&utm_campaign=devs2025
    imageUrl: https://assets.devographics.com/sponsors/certificates_dev.svg
