id: css2022 # used as first part of field names
surveyId: css2022 # used as first part of field names
startedAt: October 1, 2022
endedAt: October 30, 2022
questionsUrl: https://survey.devographics.com/survey/state-of-css/2022
resultsUrl: https://2022.stateofcss.com/
year: 2022
status: 3 # preview/open/closed/hidden
resultsStatus: 3 # hidden/preview/published
# imageUrl: https://static.devographics.com/stateofcss/2021/images/stateofcss2021.png
imageUrl: https://devographics.github.io/surveys/state_of_css/css2022/images/css2022.png
faviconUrl: https://devographics.github.io/surveys/state_of_css/css2022/images/css2022-favicon.svg
socialImageUrl: https://devographics.github.io/surveys/state_of_css/css2022/images/css2022-og.png

enableChartSponsorships: true

colors:
  primary: rgb(239, 78, 136)
  secondary: "#3633B7"
  text: rgb(255, 246, 230)
  background: rgb(39, 35, 37)
  backgroundSecondary: rgb(62, 48, 54)

credits:
  - id: lea_verou
    role: survey_design
  - id: nicole_sullivan
    role: survey_design
  - id: philip_jagenstedt
    role: survey_design
  - id: christopher_kirk_nielsen
    role: logo_design

tags:
  - css

partners:
  - name: Nijibox
    id: nijibox
    url: https://www.nijibox.jp/
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2022/images/sponsors/nijibox.svg

sponsors:
  - name: Frontend Masters
    id: frontendmasters
    url: https://frontendmasters.com/?utm_source=stateofcss&utm_medium=website&utm_campaign=stateofcss2022
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2022/images/sponsors/frontend-masters-dark.png
  # - name: Polypane
  #   id: polypane
  #   url: https://polypane.app/
  #   imageUrl: https://devographics.github.io/surveys/state_of_css/css2022/images/sponsors/polypane.png
  - name: Google Chrome
    id: google_chrome
    url: https://www.google.com/chrome/?utm_source=stateofcss&utm_medium=website&utm_campaign=stateofcss2022
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2022/images/sponsors/google.png
  # - name: Nijibox
  #   id: nijibox
  #   url: https://www.nijibox.jp/?utm_source=stateofcss&utm_medium=website&utm_campaign=stateofcss2022
  #   imageUrl: https://devographics.github.io/surveys/state_of_css/css2022/images/sponsors/nijibox.svg
  - name: RenderATL
    id: renderatl
    url: https://www.renderatl.com/?utm_source=stateofcss&utm_medium=website&utm_campaign=stateofcss2022
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2022/images/sponsors/renderatl.png

tshirt:
  images: ["shirt-mockup.jpg", "css2021-tshirt.png", "shirt-lean.jpg"]
  url: https://cottonbureau.com/products/css-retro-vhs
  price: 29
  designerUrl: https://chriskirknielsen.com/
