query {
  surveys {
    state_of_devs {
      devs2026 {
        workplace {
          work_areas_vs_years_of_experience: work_areas {
            id
            comments {
              currentEdition {
                count
              }
            }
            _correlations {
              questionCorrelations {
                kind1
                kind2
                questionId1
                sectionId1
                optionId1
                questionId2
                sectionId2
                optionId2
                n
                correlation
                sameSection
                strength
                direction
              }
              optionCorrelations {
                id
                correlations {
                  kind1
                  kind2
                  questionId1
                  sectionId1
                  optionId1
                  questionId2
                  sectionId2
                  optionId2
                  n
                  correlation
                  sameSection
                  strength
                  direction
                }
              }
            }
            combined(
              facet: career__years_of_experience
              parameters: {
                showNoAnswer: true
                cutoff: 20
                limit: 20
                sort: {
                  property: medianByFacet
                  order: asc
                }
              }
            ) {
              allEditions(editionCount: 1) {
                _metadata {
                  axis1Sort {
                    property
                    order
                  }
                  axis2Sort {
                    property
                    order
                  }
                  limit
                  cutoff
                }
                editionId
                year
                completion {
                  count
                  percentageSurvey
                  total
                }
                average
                percentiles {
                  p50
                }
                buckets {
                  count
                  id
                  value
                  index
                  percentageQuestion
                  percentageSurvey
                  isFreeformData
                  hasInsufficientData
                  averageByFacet
                  percentilesByFacet {
                    p0
                    p10
                    p25
                    p50
                    p75
                    p90
                    p100
                  }
                  facetBuckets {
                    id
                    count
                    percentageBucket
                    percentageQuestion
                    hasInsufficientData
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
