query {
  surveys {
    state_of_devs {
      devs2026 {
        career {
          negative_impacts_white_vs_non_white_1: negative_impacts {
            id
            comments {
              currentEdition {
                count
              }
            }
            _correlations {
              questionCorrelations {
                questionId1
                sectionId1
                optionId1
                questionId2
                sectionId2
                optionId2
                n
                correlation
                sameSection
                strength
                direction
              }
              optionCorrelations {
                id
                correlations {
                  questionId1
                  sectionId1
                  optionId1
                  questionId2
                  sectionId2
                  optionId2
                  n
                  correlation
                  sameSection
                  strength
                  direction
                }
              }
            }
            combined(
              filters: {
                user_info__race_ethnicity: {
                  in: [
                    white_european
                  ]
                }
              }
              parameters: {
                showNoAnswer: true
                cutoff: 20
              }
            ) {
              allEditions(editionCount: 1) {
                _metadata {
                  axis1Sort {
                    property
                    order
                  }
                  axis2Sort {
                    property
                    order
                  }
                  limit
                  cutoff
                }
                editionId
                year
                completion {
                  count
                  percentageSurvey
                  total
                }
                average
                percentiles {
                  p50
                }
                buckets {
                  count
                  id
                  value
                  index
                  percentageQuestion
                  percentageSurvey
                  isFreeformData
                  hasInsufficientData
                  entity {
                    name
                    nameHtml
                    nameClean
                    alias
                    author
                    description
                    descriptionHtml
                    descriptionClean
                    id
                    parentId
                    entityType
                    example {
                      label
                      language
                      code
                      codeHighlighted
                    }
                    avatar {
                      url
                    }
                    homepage {
                      url
                    }
                    amazon {
                      url
                    }
                    wikipedia {
                      url
                    }
                    steam {
                      url
                    }
                    youtube {
                      url
                    }
                    twitter {
                      url
                    }
                    bluesky {
                      url
                    }
                    threads {
                      url
                    }
                    twitch {
                      url
                    }
                    rss {
                      url
                    }
                    blog {
                      url
                    }
                    mastodon {
                      url
                    }
                    github {
                      url
                    }
                    npm {
                      url
                    }
                    mdn {
                      url
                    }
                    caniuse {
                      url
                    }
                    resources {
                      url
                      title
                    }
                    webFeature {
                      id
                      description_html
                      group
                      name
                      spec
                      url
                      status {
                        baseline
                        baseline_low_date
                        support {
                          chrome
                          chrome_android
                          edge
                          firefox
                          firefox_android
                          safari
                          safari_ios
                        }
                      }
                    }
                  }
                }
              }
            }
          }
          negative_impacts_white_vs_non_white_2: negative_impacts {
            id
            comments {
              currentEdition {
                count
              }
            }
            _correlations {
              questionCorrelations {
                questionId1
                sectionId1
                optionId1
                questionId2
                sectionId2
                optionId2
                n
                correlation
                sameSection
                strength
                direction
              }
              optionCorrelations {
                id
                correlations {
                  questionId1
                  sectionId1
                  optionId1
                  questionId2
                  sectionId2
                  optionId2
                  n
                  correlation
                  sameSection
                  strength
                  direction
                }
              }
            }
            combined(
              filters: {
                user_info__race_ethnicity: {
                  nin: white_european
                }
              }
              parameters: {
                showNoAnswer: true
                cutoff: 20
              }
            ) {
              allEditions(editionCount: 1) {
                _metadata {
                  axis1Sort {
                    property
                    order
                  }
                  axis2Sort {
                    property
                    order
                  }
                  limit
                  cutoff
                }
                editionId
                year
                completion {
                  count
                  percentageSurvey
                  total
                }
                average
                percentiles {
                  p50
                }
                buckets {
                  count
                  id
                  value
                  index
                  percentageQuestion
                  percentageSurvey
                  isFreeformData
                  hasInsufficientData
                  entity {
                    name
                    nameHtml
                    nameClean
                    alias
                    author
                    description
                    descriptionHtml
                    descriptionClean
                    id
                    parentId
                    entityType
                    example {
                      label
                      language
                      code
                      codeHighlighted
                    }
                    avatar {
                      url
                    }
                    homepage {
                      url
                    }
                    amazon {
                      url
                    }
                    wikipedia {
                      url
                    }
                    steam {
                      url
                    }
                    youtube {
                      url
                    }
                    twitter {
                      url
                    }
                    bluesky {
                      url
                    }
                    threads {
                      url
                    }
                    twitch {
                      url
                    }
                    rss {
                      url
                    }
                    blog {
                      url
                    }
                    mastodon {
                      url
                    }
                    github {
                      url
                    }
                    npm {
                      url
                    }
                    mdn {
                      url
                    }
                    caniuse {
                      url
                    }
                    resources {
                      url
                      title
                    }
                    webFeature {
                      id
                      description_html
                      group
                      name
                      spec
                      url
                      status {
                        baseline
                        baseline_low_date
                        support {
                          chrome
                          chrome_android
                          edge
                          firefox
                          firefox_android
                          safari
                          safari_ios
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
