id: state_of_react
hashtag: StateOfReact
domain: stateofreact.com
name: State of React
imageUrl: https://assets.devographics.com/surveys/state_of_react.png
faviconUrl: https://assets.devographics.com/surveys/state_of_react-favicon.svg

dbCollectionName: normalized_responses

emailOctopus:
  listId: e2885b7a-0691-11ee-ae17-f392ae17787f

partners:
  - name: Nijibox
    id: nijibox
    url: https://www.nijibox.jp/
    imageUrl: https://devographics.github.io/surveys/state_of_graphql/graphql2022/images/sponsors/nijibox.svg
  - name: Google Chrome
    id: google_chrome
    url: https://google.com
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2022/images/sponsors/google.png
