id: state_of_html
slug: state_of_html
hashtag: StateOfHTML
domain: stateofhtml.com
name: State of HTML

imageUrl: https://assets.devographics.com/surveys/state_of_html.png
faviconUrl: https://assets.devographics.com/surveys/state_of_html-favicon.svg

normalizedCollectionName: normalized_responses

emailOctopus:
  listId: 85cdb9aa-2c0e-11ee-80b8-e1736cb2cd4d

partners:
  - name: Nijibox
    id: nijibox
    url: https://www.nijibox.jp/
    imageUrl: https://devographics.github.io/surveys/state_of_graphql/graphql2022/images/sponsors/nijibox.svg
  - name: Google Chrome
    id: google_chrome
    url: https://google.com
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2022/images/sponsors/google.png
