id: state_of_html
slug: state_of_html
hashtag: StateOfHTML
domain: stateofhtml.com
name: State of HTML
homepageUrl: https://stateofhtml.com/

imageUrl: https://assets.devographics.com/surveys/state_of_html.png
faviconUrl: https://assets.devographics.com/surveys/state_of_html-favicon.svg

# emailOctopus:
#   listId: 85cdb9aa-2c0e-11ee-80b8-e1736cb2cd4d
# new list: just use state of js list
emailOctopus:
  listId: 463dc2a9-b2ff-11e8-a3c9-06b79b628af2
  submitUrl: https://eomail3.com/form/26a1536e-47f2-11ef-a85d-cbebfc926a4c

partners:
  - name: TokyoDev
    id: tokyodev
    url: https://www.tokyodev.com/
    imageUrl: https://assets.devographics.com/sponsors/tokyodev.svg
  - name: Google Chrome
    id: google_chrome
    url: https://google.com
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2022/images/sponsors/google.png
