id: js2025
feedbackAt: September 15, 2025
startedAt: October 15, 2025
endedAt: November 15, 2025
releasedAt: December 15, 2025
questionsUrl: https://survey.devographics.com/survey/state-of-js/2025
feedbackUrl: https://github.com/Devographics/surveys/issues/255
resultsUrl: https://2025.stateofjs.com/
year: 2025
status: 1 # preview/open/closed/hidden
resultsStatus: 1 # hidden/preview/published

enableGoal: true
enableReadingList: true
enableScore: false
enableSkip: true

responsesGoal: 10000

credits:
  # - id: shawn_wang
  #   role: survey_design
  # - id: mark_erikson
  #   role: survey_design
faq:
  - how_long_will_survey_take_js2025
  - who_should_take_survey_js
  - survey_goals_js
  - data_used_js
  - results_released_js2025
  - team
  - survey_design_js2025
  # - learn_more_js2024

colors:
  primary: rgb(71, 207, 237)
  secondary: "#8D4CA8"
  text: rgb(255, 246, 230)
  background: rgb(39, 35, 37)
  backgroundSecondary: rgb(48, 52, 53)

# partners:
#   - name: Nijibox
#     id: nijibox
#     url: https://www.nijibox.jp/
#     imageUrl: https://devographics.github.io/surveys/state_of_css/css2023/images/sponsors/nijibox.svg

sponsors:
  # - name: Polypane
  #   id: polypane
  #   url: https://polypane.app/
  #   imageUrl: https://devographics.github.io/surveys/state_of_css/css2023/images/sponsors/polypane.png
  - name: Google Chrome
    id: google_chrome
    url: https://www.google.com/chrome/?utm_source=stateofjs&utm_medium=website&utm_campaign=stateofjs2024
    imageUrl: https://assets.devographics.com/sponsors/google.png
  - name: TokyoDev
    id: tokyodev
    url: https://www.tokyodev.com/?utm_source=stateofjs&utm_medium=website&utm_campaign=stateofjs2024
    imageUrl: https://assets.devographics.com/sponsors/tokyodev.svg
  - name: Frontend Masters
    id: frontendmasters
    url: https://frontendmasters.com/?utm_source=stateofjs&utm_medium=website&utm_campaign=stateofjs2024
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2023/images/sponsors/frontend-masters-dark.png
  - name: GitNation
    id: gitnation
    url: https://gitnation.com/?utm_source=stateofjs&utm_medium=website&utm_campaign=stateofjs2024
    imageUrl: https://assets.devographics.com/sponsors/GitNation-orange.svg

  # - name: Nijibox
  #   id: nijibox
  #   url: https://www.nijibox.jp/?utm_source=stateofjs&utm_medium=website&utm_campaign=stateofjs2024
  #   imageUrl: https://devographics.github.io/surveys/state_of_css/css2023/images/sponsors/nijibox.svg
  # - name: RenderATL
  #   id: renderatl
  #   url: https://www.renderatl.com/?utm_source=stateofjs&utm_medium=website&utm_campaign=stateofjs2024
  #   imageUrl: https://devographics.github.io/surveys/state_of_css/css2023/images/sponsors/renderatl.png

tshirt:
  images: ["js2021-tshirt.jpg"]
  url: https://cottonbureau.com/products/javascript-retro-vhs
  price: 32
  designerUrl: https://chriskirknielsen.com/
# sources:
#   - id: "state_of_js_survey"
#   - id: "twitter"
#   - id: "google"
#   - id: "youtube"
#   - id: "fireship"
#   - id: "angular_community"
#   - id: "js_weekly"
#   - id: "reddit"
#   - id: "scrimba"
#   - id: "linkedin"
#   - id: "work"
#   - id: "word_of_mouth"
#   - id: "duckduckgo"
#   - id: "slack"
#   - id: "discord"
#   - id: "codrops"
#   - id: "microsoft_teams"
#   - id: "devto"
#   - id: "state_of_css_survey"
#   - id: "mastodon"
#   - id: "midudev"
#   - id: "web_standards_ru"
#   - id: "bytes"
#   - id: "facebook"
#   - id: "telegram"
#   - id: "vue_community"
#   - id: "theo_browne"
#   - id: "brave"
#   - id: "kevin_j_powell"
#   - id: "state_of_frontend"
#   - id: "elm_community"
#   - id: "james_q_quick"
#   - id: "zero_to_mastery"
#   - id: "front_end_front"
#   - id: "github"
#   - id: "svelte_community"
#   - id: "bing"
#   - id: "twitch"
#   - id: "coding_garden"
#   - id: "kode24"
#   - id: "rich_harris"
#   - id: "frontend_focus"
#   - id: "jser"
#   - id: "ryan_carniato"
#   - id: "changelog"
#   - id: "state_of_purescript"
#   - id: "eleventy"
#   - id: "hn"
#   - id: "instagram"

#   # outreach
#   - id: "shruti_kapoor"
#   - id: "afor_digital"
#   - id: "stephanie_walter"
#   - id: "self_teach_me"
#   - id: "black_girls_code"
#   - id: "diversify_tech"
#   - id: "codebar"
#   - id: "black_tech_pipeline"
#   - id: "referral_5n0w"
