id: css2025
feedbackAt: May 1, 2025
startedAt: June 1, 2025
endedAt: July 1, 2025
releasedAt: August 1, 2025
questionsUrl: https://survey.devographics.com/survey/state-of-css/2025
feedbackUrl: https://github.com/Devographics/surveys/issues/249
resultsUrl: https://2025.stateofcss.com/
year: 2025
status: 2 # preview/open/closed/hidden
resultsStatus: 1 # hidden/preview/published

enableChartSponsorships: false
enableReadingList: true
enableSkip: true

colors:
  primary: rgb(239, 78, 136)
  secondary: "#3633B7"
  text: rgb(255, 246, 230)
  background: rgb(39, 35, 37)
  backgroundSecondary: rgb(62, 48, 54)

credits:
  # - id: chen_hui_jing
  #   role: survey_design
  - id: christopher_kirk_nielsen
    role: logo_design

faq:
  - how_long_will_survey_take_css2025
  - who_should_take_survey_css
  - survey_goals_css
  - data_used_css
  - results_released_css2025
  - team
  - survey_design_css2025
  # - questions_required
  - learn_more_css2025

tags:
  - css

# partners:
#   - name: Nijibox
#     id: nijibox
#     url: https://www.nijibox.jp/
#     imageUrl: https://devographics.github.io/surveys/state_of_css/css2022/images/sponsors/nijibox.svg

sponsors:
  - name: Google Chrome
    id: google_chrome
    url: https://www.google.com/chrome/?utm_source=stateofcss&utm_medium=website&utm_campaign=css2024
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2024/images/sponsors/google.png
  - name: TokyoDev
    id: tokyodev
    url: https://www.tokyodev.com/?utm_source=stateofjs&utm_medium=website&utm_campaign=stateofjs2023
    imageUrl: https://assets.devographics.com/sponsors/tokyodev.svg
  - name: Frontend Masters
    id: frontendmasters
    url: https://frontendmasters.com/?utm_source=stateofcss&utm_medium=website&utm_campaign=css2024
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2024/images/sponsors/frontend-masters-dark.png
  - name: RenderATL
    id: renderatl
    url: https://www.renderatl.com/?utm_source=stateofcss&utm_medium=website&utm_campaign=css2024
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2024/images/sponsors/renderatl.png
  # - name: Nijibox
  #   id: nijibox
  #   url: https://www.nijibox.jp/?utm_source=stateofcss&utm_medium=website&utm_campaign=css2024
  #   imageUrl: https://devographics.github.io/surveys/state_of_css/css2022/images/sponsors/nijibox.svg
  - name: Polypane
    id: polypane
    url: https://polypane.app/?utm_source=stateofcss&utm_medium=website&utm_campaign=css2024
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2024/images/sponsors/polypane.png

tshirt:
  images: ["shirt-mockup.jpg", "css2021-tshirt.png", "shirt-lean.jpg"]
  url: https://cottonbureau.com/products/css-retro-vhs
  price: 32
  designerUrl: https://chriskirknielsen.com/

sources:
  - id: "state_of_css_survey"
  - id: "kevin_j_powell"
  - id: "twitter"
  - id: "mastodon"
  - id: "work"
  - id: "web_dev"
  - id: "youtube"
  - id: "daily_dev"
  - id: "css_weekly"
  - id: "state_of_js_survey"
  - id: "web_standards_ru"
  - id: "frontend_focus"
  - id: "miguel_angel_duran"
  - id: "google"
  - id: "other_online_sources"
  - id: "microsoft_teams"
  - id: "word_of_mouth"
  - id: "css_tricks"
  - id: "slack"
  - id: "linkedin"
