slug: state_of_graphql
hashtag: StateOfGraphQL
domain: stateofgraphql.com
name: State of GraphQL

emailOctopus:
  listId: 3fb96da2-e6d5-11ec-9258-0241b9615763

tags: 
  - graphql

partners:
  - name: Nijibox
    id: nijibox
    url: https://www.nijibox.jp/
    imageUrl: https://devographics.github.io/surveys/state_of_graphql/2022/images/sponsors/nijibox.svg
