slug: state_of_graphql
hashtag: StateOfGraphQL
domain: stateofgraphql.com
name: State of GraphQL

emailOctopus:
  listId: 3fb96da2-e6d5-11ec-9258-0241b9615763

tags: 
  - graphql

sponsors:
  - name: Frontend Masters
    id: frontendmasters
    url: https://frontendmasters.com/
    imageUrl: https://devographics.github.io/surveys/state_of_graphql/2022/images/sponsors/frontend-masters-dark.png
  - name: Nhost
    id: nhost
    url: https://nhost.io/
    imageUrl: https://devographics.github.io/surveys/state_of_graphql/2022/images/sponsors/nhost-logo-white.png
  - name: Apollo
    id: apollo
    url: https://www.apollographql.com/
    imageUrl: https://devographics.github.io/surveys/state_of_graphql/2022/images/sponsors/apollo-graphql-logo.svg
  - name: The Guild
    id: the_guild
    url: https://www.the-guild.dev/
    imageUrl: https://devographics.github.io/surveys/state_of_graphql/2022/images/sponsors/the-guild-full-white-logo.svg