id: state_of_ai
slug: state_of_ai
hashtag: StateOfAI
name: State of AI
domain: stateofai.dev

imageUrl: https://assets.devographics.com/surveys/state_of_js.png
faviconUrl: https://assets.devographics.com/surveys/state_of_js-favicon.svg

partners:
  - name: Google Chrome
    id: google_chrome
    url: https://google.com
    imageUrl: https://assets.devographics.com/sponsors/google.png
  - name: TokyoDev
    id: tokyodev
    url: https://www.tokyodev.com/
    imageUrl: https://assets.devographics.com/sponsors/tokyodev.svg
  - name: Frontend Masters
    id: frontendmasters
    url: https://frontendmasters.com/?utm_source=stateofjs&utm_medium=website&utm_campaign=stateofjs2023
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2023/images/sponsors/frontend-masters-dark.png
  - name: GitNation
    id: gitnation
    url: https://gitnation.com/?utm_source=stateofjs&utm_medium=website&utm_campaign=stateofjs2024
    imageUrl: https://assets.devographics.com/sponsors/GitNation-orange.svg
